// <auto-generated />
using System;
using Figurou.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Figurou.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260623183540_AdicionadoCampoAlbumSelecionadoUsuario")]
    partial class AdicionadoCampoAlbumSelecionadoUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Figurou.Business.Models.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ImagemCapa")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TotalFigurinhas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nome", "Ano")
                        .IsUnique();

                    b.ToTable("Albuns", (string)null);
                });

            modelBuilder.Entity("Figurou.Business.Models.Conversa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TrocaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TrocaId")
                        .IsUnique();

                    b.ToTable("Conversas", (string)null);
                });

            modelBuilder.Entity("Figurou.Business.Models.Figurinha", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NomeJogador")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<Guid>("PaginaAlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Raridade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PaginaAlbumId");

                    b.HasIndex("AlbumId", "PaginaAlbumId", "Codigo")
                        .IsUnique();

                    b.HasIndex("AlbumId", "PaginaAlbumId", "Numero")
                        .IsUnique();

                    b.ToTable("Figurinhas", (string)null);
                });

            modelBuilder.Entity("Figurou.Business.Models.FigurinhaUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DisponivelTroca")
                        .HasColumnType("bit");

                    b.Property<Guid>("FigurinhaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("PossuiNoAlbum")
                        .HasColumnType("bit");

                    b.Property<int>("QuantidadeRepetida")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FigurinhaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("FigurinhasUsuario", (string)null);
                });

            modelBuilder.Entity("Figurou.Business.Models.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Compatibilidade")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioDestinoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioOrigemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioDestinoId");

                    b.HasIndex("UsuarioOrigemId", "UsuarioDestinoId")
                        .IsUnique();

                    b.ToTable("Matches", null, t =>
                        {
                            t.HasCheckConstraint("CK_Match_Compatibilidade", "[Compatibilidade] >= 0 AND [Compatibilidade] <= 100");
                        });
                });

            modelBuilder.Entity("Figurou.Business.Models.Mensagem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("ConversaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Editada")
                        .HasColumnType("bit");

                    b.Property<bool>("Excluida")
                        .HasColumnType("bit");

                    b.Property<bool>("Lida")
                        .HasColumnType("bit");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ConversaId");

                    b.HasIndex("DataEnvio");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Mensagens", (string)null);
                });

            modelBuilder.Entity("Figurou.Business.Models.PaginaAlbum", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Altura")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("ImagemPagina")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Largura")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("NumeroPagina")
                        .HasColumnType("int");

                    b.Property<Guid?>("SelecaoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("SelecaoId");

                    b.HasIndex("AlbumId", "NumeroPagina")
                        .IsUnique();

                    b.ToTable("PaginasAlbum", (string)null);
                });

            modelBuilder.Entity("Figurou.Business.Models.Selecao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("AlbumId", "Codigo")
                        .IsUnique();

                    b.HasIndex("AlbumId", "Nome")
                        .IsUnique();

                    b.ToTable("Selecoes", (string)null);
                });

            modelBuilder.Entity("Figurou.Business.Models.SlotPaginaAlbum", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Altura")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<Guid>("FigurinhaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Largura")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<Guid>("PaginaAlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PosicaoX")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("PosicaoY")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("Id");

                    b.HasIndex("FigurinhaId")
                        .IsUnique();

                    b.HasIndex("PaginaAlbumId");

                    b.HasIndex("PaginaAlbumId", "Ordem")
                        .IsUnique();

                    b.ToTable("SlotsPaginaAlbum", (string)null);
                });

            modelBuilder.Entity("Figurou.Business.Models.Troca", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRequisicao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DestinatarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Observacao")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("SolicitanteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinatarioId");

                    b.HasIndex("SolicitanteId");

                    b.HasIndex("Status");

                    b.ToTable("Trocas", (string)null);
                });

            modelBuilder.Entity("Figurou.Business.Models.TrocaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FigurinhaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<Guid>("TrocaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FigurinhaId");

                    b.HasIndex("TrocaId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("TrocaId", "UsuarioId", "FigurinhaId")
                        .IsUnique();

                    b.ToTable("TrocaItens", (string)null);
                });

            modelBuilder.Entity("Figurou.Business.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AlbumEscolhidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Papel")
                        .HasColumnType("int");

                    b.Property<string>("SenhaCodificada")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumEscolhidoId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Figurou.Business.Models.UsuarioDetalhe", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Experiencia")
                        .HasColumnType("int");

                    b.Property<string>("Imagem")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Reputacao")
                        .HasColumnType("int");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Cidade");

                    b.HasIndex("Estado");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("UsuarioDetalhes", (string)null);
                });

            modelBuilder.Entity("Figurou.Business.Models.Conversa", b =>
                {
                    b.HasOne("Figurou.Business.Models.Troca", "Troca")
                        .WithOne()
                        .HasForeignKey("Figurou.Business.Models.Conversa", "TrocaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Troca");
                });

            modelBuilder.Entity("Figurou.Business.Models.Figurinha", b =>
                {
                    b.HasOne("Figurou.Business.Models.Album", "Album")
                        .WithMany("Figurinhas")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Figurou.Business.Models.PaginaAlbum", "PaginaAlbum")
                        .WithMany("Figurinhas")
                        .HasForeignKey("PaginaAlbumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("PaginaAlbum");
                });

            modelBuilder.Entity("Figurou.Business.Models.FigurinhaUsuario", b =>
                {
                    b.HasOne("Figurou.Business.Models.Figurinha", "Figurinha")
                        .WithMany("FigurinhasUsuario")
                        .HasForeignKey("FigurinhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Figurou.Business.Models.Usuario", "Usuario")
                        .WithMany("FigurinhasUsuario")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Figurinha");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Figurou.Business.Models.Match", b =>
                {
                    b.HasOne("Figurou.Business.Models.Usuario", "UsuarioDestino")
                        .WithMany("MatchesRecebidos")
                        .HasForeignKey("UsuarioDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Figurou.Business.Models.Usuario", "UsuarioOrigem")
                        .WithMany("MatchesSolicitados")
                        .HasForeignKey("UsuarioOrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioDestino");

                    b.Navigation("UsuarioOrigem");
                });

            modelBuilder.Entity("Figurou.Business.Models.Mensagem", b =>
                {
                    b.HasOne("Figurou.Business.Models.Conversa", "Conversa")
                        .WithMany("Mensagens")
                        .HasForeignKey("ConversaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Figurou.Business.Models.Usuario", "Usuario")
                        .WithMany("Mensagens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Figurou.Business.Models.PaginaAlbum", b =>
                {
                    b.HasOne("Figurou.Business.Models.Album", "Album")
                        .WithMany("Paginas")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Figurou.Business.Models.Selecao", "Selecao")
                        .WithMany("PaginasAlbum")
                        .HasForeignKey("SelecaoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Album");

                    b.Navigation("Selecao");
                });

            modelBuilder.Entity("Figurou.Business.Models.Selecao", b =>
                {
                    b.HasOne("Figurou.Business.Models.Album", "Album")
                        .WithMany("Selecoes")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Figurou.Business.Models.SlotPaginaAlbum", b =>
                {
                    b.HasOne("Figurou.Business.Models.Figurinha", "Figurinha")
                        .WithMany("SlotsPaginaAlbum")
                        .HasForeignKey("FigurinhaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Figurou.Business.Models.PaginaAlbum", "PaginaAlbum")
                        .WithMany("SlotsPaginaAlbum")
                        .HasForeignKey("PaginaAlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Figurinha");

                    b.Navigation("PaginaAlbum");
                });

            modelBuilder.Entity("Figurou.Business.Models.Troca", b =>
                {
                    b.HasOne("Figurou.Business.Models.Usuario", "Destinatario")
                        .WithMany("TrocasRecebidas")
                        .HasForeignKey("DestinatarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Figurou.Business.Models.Usuario", "Solicitante")
                        .WithMany("TrocasSolicitadas")
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destinatario");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("Figurou.Business.Models.TrocaItem", b =>
                {
                    b.HasOne("Figurou.Business.Models.Figurinha", "Figurinha")
                        .WithMany("TrocaItens")
                        .HasForeignKey("FigurinhaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Figurou.Business.Models.Troca", "Troca")
                        .WithMany("TrocaItens")
                        .HasForeignKey("TrocaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Figurou.Business.Models.Usuario", "Usuario")
                        .WithMany("TrocaItens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Figurinha");

                    b.Navigation("Troca");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Figurou.Business.Models.Usuario", b =>
                {
                    b.HasOne("Figurou.Business.Models.Album", "Album")
                        .WithMany("AlbunsEscolhidosUsuarios")
                        .HasForeignKey("AlbumEscolhidoId");

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Figurou.Business.Models.UsuarioDetalhe", b =>
                {
                    b.HasOne("Figurou.Business.Models.Usuario", "Usuario")
                        .WithOne("UsuarioDetalhes")
                        .HasForeignKey("Figurou.Business.Models.UsuarioDetalhe", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Figurou.Business.Models.Album", b =>
                {
                    b.Navigation("AlbunsEscolhidosUsuarios");

                    b.Navigation("Figurinhas");

                    b.Navigation("Paginas");

                    b.Navigation("Selecoes");
                });

            modelBuilder.Entity("Figurou.Business.Models.Conversa", b =>
                {
                    b.Navigation("Mensagens");
                });

            modelBuilder.Entity("Figurou.Business.Models.Figurinha", b =>
                {
                    b.Navigation("FigurinhasUsuario");

                    b.Navigation("SlotsPaginaAlbum");

                    b.Navigation("TrocaItens");
                });

            modelBuilder.Entity("Figurou.Business.Models.PaginaAlbum", b =>
                {
                    b.Navigation("Figurinhas");

                    b.Navigation("SlotsPaginaAlbum");
                });

            modelBuilder.Entity("Figurou.Business.Models.Selecao", b =>
                {
                    b.Navigation("PaginasAlbum");
                });

            modelBuilder.Entity("Figurou.Business.Models.Troca", b =>
                {
                    b.Navigation("TrocaItens");
                });

            modelBuilder.Entity("Figurou.Business.Models.Usuario", b =>
                {
                    b.Navigation("FigurinhasUsuario");

                    b.Navigation("MatchesRecebidos");

                    b.Navigation("MatchesSolicitados");

                    b.Navigation("Mensagens");

                    b.Navigation("TrocaItens");

                    b.Navigation("TrocasRecebidas");

                    b.Navigation("TrocasSolicitadas");

                    b.Navigation("UsuarioDetalhes");
                });
#pragma warning restore 612, 618
        }
    }
}
